/**
 * Sponsor images are resolved dynamically at runtime from a manifest file
 * (generated by scripts/generate-sponsor-images-manifest.mjs) that lists
 * whatever image files currently exist in this folder. Nothing here
 * hardcodes an actual image filename — just drop a new image into
 * `src/assets/img/sponsors` and it will automatically appear in the carousel.
 */
export const SPONSOR_IMAGE_BASE_PATH = '/assets/img/sponsors/';
export const SPONSOR_MANIFEST_PATH = `${SPONSOR_IMAGE_BASE_PATH}manifest.json`;

export const SPONSOR_CAROUSEL_INTERVAL_SECONDS = 30;
